apiVersion: v1
kind: Service
metadata:
  name: volley-backend-svc
  labels:
    {{- include "bubelu-volley.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.backend }}
  selector:
    app: vbcl
    tier: backend
    {{- include "bubelu-volley.selectorLabels" . | nindent 4 }}
