CREATE SEQUENCE hibernate_sequence START 1;


CREATE TABLE T_TASK (

  ID serial PRIMARY KEY,
  DATUM date,
  BESCHREIBUNG VARCHAR(255) NOT NULL,
  DAUER VARCHAR(255),
  NAME_RESERVATION VARCHAR(255),
  ID_RESERVATION VARCHAR(255),
  BESTAETIGT Boolean

)