name: vbcl_backend_deploy


on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: docker Login
        run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag toky03/vbcl-backend:1.1.${{ github.run_number }}
      - name: Push the Docker image
        run: docker push toky03/vbcl-backend:1.1.${{ github.run_number }}
  deployment:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Deploy
        run: |
          cd helm
          helm upgrade --install --atomic --timeout 1m volley . -f ./values.yaml \
            --kube-context github-deploy-volley-kubernetes --namespace volley \
            --set image.tag=1.1.${{ github.run_number }}
