name: vbcl_backend_deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: 'ubuntu-latest'
      steps:
        - uses: actions/checkout@v2
        - name: docker Login
          run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag toky03/vbcl-backend:1.1..${{ github.run_number }}
        - name: Push the Docker image
          run: docker push toky03/vbcl-backend:1.1..${{ github.run_number }}
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - working-directory: helm
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          helm: helm3
          release: 'volley'
          namespace: 'volley'
          chart: 'volley-app'
          token: '${{ github.token }}'
          values: |
            image:
              tag: 1.1.${{ github.run_number }}
          value-files: ["values.yaml"]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'