name: vbcl_backend_deploy

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ./helm
    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          helm: helm3
          release: 'volley'
          namespace: 'volley'
          chart: 'volley-app'
          token: '${{ github.token }}'
          values: |
            image:
              tag: 1.1.10
          value-files: "values.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'